### ISSUE TITLE
How to change in the Podfile to set CODE_SIGNING_REQUIRED with NO

### ISSUE THREAD

**Issue by hanatharesh2712** [damienaicheh/iOSPipeline#2]
As mentioned in the blog, We need to open the Podfile and add the below lines of code in the file.
```
post_install do |installer|
        installer.pods_project.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
end
```

so, My question is, how to add these lines of code using Azure pipeline tasks? Can you post here how you managed this in CI pipeline?
I am using Ionic Cordova for building the app.
Thanks!

**Comment by damienaicheh** [comment]
Hello,

Just edit the Podfile in your project and push it in your git repository. Nothing more to do :)

**Comment by hanatharesh2712** [comment]
@damienaicheh Thanks for replying.. but, As I mentioned I am building the ios app using the Cordova in Azure pipeline and the ios project added dynamically when I run the command like: `ionic cordova build ios`

so, every time the CI pipeline runs it generates all these files dynamically.
Is there any workaround like passing the arguments in the xcodebuild command or something?

**Comment by damienaicheh** [comment]
Ok I see the issue.
If cordova doesn't give you the ability to override this the only idea I have is to do a bash script to change these lines but I m surprise that you can't definee your own Podfile or override some properties. It seems to be a basic behavior for me.

**Comment by hanatharesh2712** [comment]
Thanks for your suggestion!
Do you think it is an Xcode Azure pipeline task issue? It was successfully building the app with Xcode 10. And I upgraded it to Xcode 12 and facing these issues.

**Comment by damienaicheh** [comment]
No I think it's more an iOS issue probably with new updates of Xcode. I m sure Cordova has a way to handle this. It's sound pretty basic.

**Comment by hanatharesh2712** [comment]
@damienaicheh because In my Mac system Xcode does not create any issues and In the Podfile, there is no code written for  CODE_SIGNING_REQUIRED=NO. I encounter the issue only when I run the Azure build pipeline.
